# ミス
非同期処理(async/await)でループ処理(for)をした時に、breakで抜けてしまった

## 問題点
ループを抜けても関数が終了しない

## 対策
`return`を使用し早期リターンを行う。  
- `return`: 関数コンテキストの即時解放
- `break`: ループコンテキストのみ解放